title: ruvieye's log
email: ruvieye@naver.com
description: Continuous devlog
author: ruvieye
baseurl: ""
url: "http://ruvieye.github.io"

# Social Profiles
twitter_username: ruvieye
github_username: ruvieye
facebook_username: ruvieye

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: true
    block:
      line_numbers: true
      start_line: 1

paginate: 7
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist